### PR TITLE
Document: Trello link

### PR DESCRIPTION
**Pull request by avisionh**
# Summary
This branch adds a small change to include our Trello board link to the README.

# Check
- [x] Trello link works.
- [x] The travis.ci and R CMD checks pass.

### CODE REVIEW

**Comment by avisionh** [comment]
[Review PR: Trello links](https://trello.com/c/HIcWqhJ6/59-review-pr-trello-links)

**Review by gabtam55 — COMMENTED** [review]
- You added 'This branch adds a small change to include our Trello board link to the README.' to the README.md instead of 'You can find out about our current backlog of work on our public Trello [Doing board](https://trello.com/b/n5l7DMS5/doing).'. Am I correct?

- The travis.ci and R CMD checks pass.

**Comment by avisionh** [comment]
> * You added 'This branch adds a small change to include our Trello board link to the README.' to the README.md instead of 'You can find out about our current backlog of work on our public Trello [Doing board](https://trello.com/b/n5l7DMS5/doing).'. Am I correct?
> * The travis.ci and R CMD checks pass.

Oh my, I'm such an idiot. Updated now!

**Comment by gabtam55** [comment]
> > * You added 'This branch adds a small change to include our Trello board link to the README.' to the README.md instead of 'You can find out about our current backlog of work on our public Trello [Doing board](https://trello.com/b/n5l7DMS5/doing).'. Am I correct?
> > * The travis.ci and R CMD checks pass.
> 
> Oh my, I'm such an idiot. Updated now!

I do this all the time! For some reason, the R CMD check does not pass now!

**Comment by avisionh** [comment]
> > > * You added 'This branch adds a small change to include our Trello board link to the README.' to the README.md instead of 'You can find out about our current backlog of work on our public Trello [Doing board](https://trello.com/b/n5l7DMS5/doing).'. Am I correct?
> > > * The travis.ci and R CMD checks pass.
> > 
> > 
> > Oh my, I'm such an idiot. Updated now!
> 
> I do this all the time! For some reason, the R CMD check does not pass now!

Yes, super annoying, need to investigate further! 😢 

#### Update 1
Ran the checks locally via `devtools::check()` and didn't come across any errors nor warnings so manually re-running these jobs on GitHub.
image

#### Update 2
I brute forced my way by manually re-running these jobs until they succeeded - probably not the best way to do it but there really shouldn't be errors coming up in the first place. I blame dodgy builds.

**Review by gabtam55 — APPROVED** [review]

**Pull request merged**
