### PR TITLE
Format: Modularise

### LINKED ISSUE #26: Modularise Shiny code
Example [here](https://github.com/rpodcast/ames_explorer)

This is to follow good software-development practice.

Documentation available on RStudio website [here](https://shiny.rstudio.com/articles/modules.html).

### LINKED ISSUE #46: Discuss: Position logo in left sidebar
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see the logo more clearly.

**Describe the solution you'd like**
It might be better to have the logo in the bottom-left like below?

image

**Describe alternatives you've considered**
Where it is currently positioned is quite small and hard to see.

**Additional context**
Website is [here](https://hssgenomics.shinyapps.io/RNAseq_DRaMA/).

Code base is [here](https://gitlab.com/hssgenomics/Shiny).

### LINKED ISSUE #67: fix: Setup instructions should include using R version 3.6.2 and running renv::restore()
**Describe the bug**
Installation fails because the environment is not setup first
running renv::restore fails because of incorrect R version or missing external dependencies

### PR DESCRIPTION
**Pull request by avisionh**
# Summary
This branch modularises our Shiny code (predominantly the code in the `server.R` script) to ensure that we isolate independent logic. In this way, we are improving the ease of understanding the different components of the Shiny app, and thereby increasing readability.

# Changes
The changes made in this PR are:
1. Create `modules/` folder to store the modules we are creating of each rendered object.
1. Rename some objects to be more explicit.
1. Move the generated text in the `ui.R` script into the `server.R` script to prepare it for translation.
    + In essence, they will actually exist as modules within the `server.R` script.

***

# Check
- [x] The app looks the same as it did before.
- [x] The logo is in the bottom-left
    + This was to prevent the top green bar overflowing when viewed on mobiles.
- [x] The travis.ci and R CMD checks pass.

***

## Note
This "fixes #26", "fixes #46" and "fixes #67" and progresses #74.

### CODE REVIEW

**Comment by avisionh** [comment]
[Modularise Shiny code](https://trello.com/c/VxbXFs7Q/41-modularise-shiny-code)

**Comment by gabtam55** [comment]
Thanks for doing this. I was trying to look at the app by running the `app.R` script. When I ran renv::restore() to make sure I have the right packages, the error message `Error: install of package 'nlme' failed` appeared. Did the same happen to you?

**Comment by avisionh** [comment]
> Thanks for doing this. I was trying to look at the app by running the `app.R` script. When I ran renv::restore() to make sure I have the right packages, the error message `Error: install of package 'nlme' failed` appeared. Did the same happen to you?

This is very strange. I just cloned the whole repo and ran `renv::restore()` but didn't get the same issue. Is `nlme` in your `renv.lock` file already?

**Comment by gabtam55** [comment]
> > Thanks for doing this. I was trying to look at the app by running the `app.R` script. When I ran renv::restore() to make sure I have the right packages, the error message `Error: install of package 'nlme' failed` appeared. Did the same happen to you?
> 
> This is very strange. I just cloned the whole repo and ran `renv::restore()` but didn't get the same issue. Is `nlme` in your `renv.lock` file already?

I tried again and had the same issue unfortunately. I am not sure if this helps but do you mind to update the packages and take a renv snapshot? I will then try again. Thanks!

**Comment by avisionh** [comment]
> I tried again and had the same issue unfortunately. I am not sure if this helps but do you mind to update the packages and take a renv snapshot? I will then try again. Thanks!

That's a good suggestion, done it now!

**Comment by avisionh** [comment]
> Thanks for doing this. I was trying to look at the app by running the `app.R` script. When I ran renv::restore() to make sure I have the right packages, the error message `Error: install of package 'nlme' failed` appeared. Did the same happen to you?

I managed to replicate the issue by moving to R version 4.0.2 and then trying to `renv::restore()`. Coming across another issue now with the `sf` package not installing on the new R version and are going to try resolve it by consulting the following links:
- [cannot install sf package](https://github.com/r-spatial/sf/issues/1393)
- [cannot install sf package on macOS Sierra](https://github.com/r-spatial/sf/issues/680)
- [unable to install package on R](https://stackoverflow.com/questions/60116363/unable-to-install-a-package-on-r)

**Comment by avisionh** [comment]
Should be sorted now. @gabtam55, can you try again?

**Comment by gabtam55** [comment]
> Should be sorted now. @gabtam55, can you try again?

It looks good to me, well done! Feel free to merge ;)

**Review by gabtam55 — APPROVED** [review]

**Pull request merged**
