### PR TITLE
Feature: Map

### LINKED ISSUE #13: Add mapping functionality
Would be cool to include maps of each constituency.

Already have shapefiles (woohoo!) of each district provided by [ESRI China](http://opendata.esrichina.hk/datasets/eea8ff2f12b145f7b33c4eef4f045513_0).

Need a mapping from constituency (spreadsheet) to districts (ESRI).

### LINKED ISSUE #24: Allow users to type district in search
Improves the user-experience as currently, they cannot search by typing unless they type super quickly.

### PR DESCRIPTION
**Pull request by avisionh**
# Summary
This branch adds the map functionality to the Shiny app.

# Changes
The changes made in this PR are:
1. Loads in shapefiles for:
    + Hong Kong
    + District Councils
1. Uses `ggplot2` to plot the shapefiles.
1. Highlights the district council the user has selected.
1. Enables search by typing.

image

...

# Check
- [x] The map of HK and district councils is clear.
- [x] The right district is highlighted when the user chooses a district.
- [x] The user can search by typing a district in the search box.
- [x] The R CMD and travis.ci checks pass.
- [x] MIT License badge is on the README.md
- [x] Links to prod and pre-prod web-hosted version of apps are on README.md and work.
- [x] @ocean0609's logo is now in the top-right of the webpage. 
...

# Note
This "fixes #13" and "fixes #24".

The shapefiles for the maps are stored in the repo. This is because they cannot be imported from GDrive.

Is currently deployed on [pre-prod](https://hkdistricts-info.shinyapps.io/dashboard-hkdistrictcouncillors-preprod/).

### CODE REVIEW

**Comment by avisionh** [comment]
Now need to be able to join the HK DC shape file, `shape_district` with the Gsheet, `data_master_raw`. This is so we can link the user input with what's displayed on the map.
 
@martinctc and @justin-yim, will you be able to do this? I'm not entirely sure how to do it myself.

**Comment by avisionh** [comment]
> Now need to be able to join the HK DC shape file, `shape_district` with the Gsheet, `data_master_raw`. This is so we can link the user input with what's displayed on the map.
> 
> @martinctc and @justin-yim, will you be able to do this? I'm not entirely sure how to do it myself.

Actually, think I managed to join it. Looks like can do so via constituency code which are provided in both datasets!

**Comment by avisionh** [comment]
Build is failing because it doesn't know where the shapefiles are. Cannot link to GDrive so will have to include the shapefiles into the repo.

**Comment by martinctc** [comment]
The corresponding .dbf and .shx files have to be in the same directory of the .shp files in order for the shape files to work. 
See: https://stackoverflow.com/a/58820909/5539702

Will add these back in the next commit!

**Comment by martinctc** [comment]
I'm experiencing an issue where I can't run the map properly, even after adding the associated shape files:

image

**Comment by avisionh** [comment]
> I'm experiencing an issue where I can't run the map properly, even after adding the associated shape files:
> 
> image

Figured out what the issue is. Need all the shapefiles for this. Re-included them back in with the latest commit.

**Comment by martinctc** [comment]
Fantastic stuff! Looks good. One potential enhancement in the future would be to make the search more 'fuzzy', e.g. for "HO MAN TIN", some might put "HOMANTIN" (both are known acceptable spellings).

**Review by martinctc — APPROVED** [review]

**Pull request merged**
